version: 2
updates:
  - package-ecosystem: github-actions
    directory: "/"
    schedule:
      interval: weekly
      day: "monday"
      time: "07:00"
      timezone: "America/Sao_Paulo"
    open-pull-requests-limit: 10

  - package-ecosystem: docker
    directory: "/dockerfiles"
    schedule:
      interval: weekly
      day: "monday"
      time: "07:00"
      timezone: "America/Sao_Paulo"
    open-pull-requests-limit: 10

  - package-ecosystem: composer
    directory: "/dockerfiles"
    schedule:
      interval: weekly
      day: "monday"
      time: "07:00"
      timezone: "America/Sao_Paulo"
    open-pull-requests-limit: 10

  - package-ecosystem: pip
    directory: "/"
    schedule:
      interval: weekly
      day: "monday"
      time: "07:00"
      timezone: "America/Sao_Paulo"
    open-pull-requests-limit: 10
