services:
  app:
    container_name: task-management-app
    build:
      context: ..
      dockerfile: dockerfiles/Dockerfile.dev
      target: development
    ports:
      - "8000:8000"
    volumes:
      # Mount source code for hot reloading
      - ../src:/app/src:cached
      - ../tests:/app/tests:cached
      - /app/.venv
    env_file:
      - ../.env
    environment:
      # Override database host for container networking
      - POSTGRES_HOST=db
    depends_on:
      db:
        condition: service_healthy
    networks:
      - task_management_network
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  db:
    container_name: postgres-db
    image: postgres:17-alpine
    environment:
      POSTGRES_DB: ${POSTGRES_DB:-task_management_db}
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-postgres}
      # Performance tuning for development
      POSTGRES_INITDB_ARGS: "--encoding=UTF-8 --lc-collate=C --lc-ctype=C"
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ../scripts/init-db.sql:/docker-entrypoint-initdb.d/init-db.sql:ro
    networks:
      - task_management_network
    restart: unless-stopped
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "pg_isready -U ${POSTGRES_USER:-postgres} -d ${POSTGRES_DB:-task_management_db}",
        ]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s

volumes:
  postgres_data:

networks:
  task_management_network:
    driver: bridge
